name: demo
on:
  push:
    branches: [main]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: log hello
        run: |
            echo Hello!
            echo What is file?
            ls -l
            echo Wow!
      - name: demo
        run: ls -a